### ISSUE TITLE
Http basic authentication.

### ISSUE THREAD

**Issue by SamuelMeza** [jlucansky/Camunda.Api.Client#1]
Hi there,

I am looking forward to using your library for a project, but I need the ability to use basic http authentication from it, which seems to be missing, would you consider pushing a new change to the CamundaClient.cs that would allow passing an HttpClient object in a new constructor so RestService.For<I> can be called using a string or the HttpClient object? I am attaching the patch.

[patch.txt](https://github.com/jlucansky/Camunda.Api.Client/files/714791/patch.txt)

Thank you for considering this and hoping this may make it to your library & the corresponding NuGet
 package.

Best Regards.
Samuel Meza

**Comment by jlucansky** [comment]
Hi, sorry for late reponse, I didn't get any notification. Your change is now available in 1.0.3 version.

**Comment by SamuelMeza** [comment]
Hey Jan, this is so great, thank you very much!
