### ISSUE TITLE
BadRequest Exception on calling client.UserTasks[id].Variables.SetBinary()

### ISSUE THREAD

**Issue by mjalil** [jlucansky/Camunda.Api.Client#10]
Hi @jlucansky,
I faced with an internal exception on calling `client.UserTasks[id].Variables.SetBinary`. the server returns error 400 BadRequest. I got the source and stepped into SetBinary and then stepped into Refit to find out the reason of Bad Request. Guess what, the `data` and `valueType` is serialized as `application/json`.

You could test it with a unit test or at least read response error content and throw BadRequestException with more detail.

However, this is a lack of feature in Refit that I will ask them for support of HttpContent in Multipart

**Comment by jlucansky** [comment]
Fixed in latest refit 4.6.16
