### ISSUE TITLE
Add functionality for DELETE deployment/{id}?cascade=true

### ISSUE THREAD

**Issue by nicojs** [jlucansky/Camunda.Api.Client#11]
As of now, it is not possible to use the cascade=true function from the C# api. This is a useful feature, especially when writing integration tests (easy way to clear the database).

**Comment by jlucansky** [comment]
Added in https://github.com/jlucansky/Camunda.Api.Client/commit/53afd4fe0013d1f7e6d95a20ae8f2217845e0805
