### ISSUE TITLE
Delete with cascade: true doesn't work.

### ISSUE THREAD

**Issue by nicojs** [jlucansky/Camunda.Api.Client#17]
Calling `client.Deployments[deployment.Id].Delete(cascade: true)` doesn't work. It results in an HTTP 500 response with a response message like:

```
ENGINE-03076 Deletion of process definition without cascading failed. Process definition with id: 7821f9ad-7b76-11e8-9145-0242ac120004 can't be deleted, since there exists 1 dependening process instances.
```

After some more digging, I found that the HTTP call being done is:

```
HTTP DELETE /deployment/7820730b-7b76-11e8-9145-0242ac120004?cascade=True&skipCustomListeners=False&skipIoMappings=False
```

This should be (difference is in casing)

```
HTTP DELETE /deployment/7820730b-7b76-11e8-9145-0242ac120004?cascade=true&skipCustomListeners=false&skipIoMappings=false
```

**Comment by jlucansky** [comment]
Please update to latest version. Should be fixed already https://github.com/jlucansky/Camunda.Api.Client/commit/47df4e8cd4623fdbd07d9b31dd1e571c9e8774ba

**Comment by nicojs** [comment]
Version 2.0.2 still has the issue.

**Comment by nicojs** [comment]
The latest version being 2.0.2? That has the issue.

**Comment by jlucansky** [comment]
I see. Commit was unfortunately discarded with some later merge. Thank you for report.

**Comment by MickProPay** [comment]
Is this issues fixed??
