### ISSUE TITLE
support sending Signals with "/signal"

### ISSUE THREAD

**Issue by firle** [jlucansky/Camunda.Api.Client#19]
Since Camunda Platform 7.8 there is an additional route "/signal" to send signals to specified executions or to all subscribed handler. It would be super cool, if you can manage to implement this. Unfortunately i don't have time for that yet.

greets Ephraim

**Comment by asalhani** [comment]
@flyingpie does this means that your repo at MyGet is more updated than this one in Github? I mean which one should I use (MyGet or Github)?

Thanks...

**Comment by flyingpie** [comment]
@asalhani Currently, the NuGet package at MyGet contains all the changes proposed in the PR here: https://github.com/jlucansky/Camunda.Api.Client/pull/24. You can use that one until the PR is completed and the main package from NuGet gets updated.

**Comment by asalhani** [comment]
@flyingpie thanks for the clarification...

**Comment by jlucansky** [comment]
Avaiable in 2.1.0
