### ISSUE TITLE
Support for lots of API's introduced since 7.5

### ISSUE THREAD

**Issue by flyingpie** [jlucansky/Camunda.Api.Client#21]
@jlucansky Two questions:

- I've been working on adding support for additional endpoints not yet available in the master branch, are you interested in having these in a PR?
- If so, because of the amount of stuff, would you prefer one big PR, or separate PR's per endpoint for example?

Example PR is here: https://github.com/flyingpie/Camunda.Api.Client/pull/1

**Comment by jlucansky** [comment]
Wow thank you very much this is huge contribution. It can be single PR, I must review it either way.

**Comment by flyingpie** [comment]
@jlucansky Thank you for the quick response, I'm gonna do some finishing up and send you a PR.

**Comment by asalhani** [comment]
@flyingpie thanks for your contribution. Any update on the PR so far?

**Comment by flyingpie** [comment]
@asalhani You can find the PR here: https://github.com/jlucansky/Camunda.Api.Client/pull/24

Currently waiting for @jlucansky to review the changes.

**Comment by jlucansky** [comment]
I was currently busy but don't worry I will merge PR soon. It's huge update.

**Comment by flyingpie** [comment]
> 
> 
> I was currently busy but don't worry I will merge PR soon. It's huge update.

Didn't mean any pressure, please take as much time as you need :)

**Comment by jlucansky** [comment]
Merged :)
