### ISSUE TITLE
Add functionality for DELETE /process-instance/{id}?skipIoMappings=true

### ISSUE THREAD

**Issue by bhutten14** [jlucansky/Camunda.Api.Client#22]
Hi,

Please add support for the query parameters for delete processinstance.
Query parameters are: skipCustomListeners, skipIoMappings, skipSubprocesses.

Kind regards,
Berthold

**Comment by bhutten14** [comment]
See PR https://github.com/jlucansky/Camunda.Api.Client/pull/23

**Comment by jlucansky** [comment]
Merged
