### ISSUE TITLE
DateTime(Offset)

### ISSUE THREAD

**Issue by flyingpie** [jlucansky/Camunda.Api.Client#26]
So it occurred to me that Camunda internally uses Joda Time, which includes time zone information (eg. offsets).

As of now, the client api encapsulates these using System.DateTime. I have a proposed changeset in here, changing these to System.DateTimeOffset, including a bit of serialization fluff: https://github.com/flyingpie/Camunda.Api.Client/pull/3.

Though, I would really like some unit tests before rolling this into master.

Now, here are some thoughts:

- We could extent the unit test project, though I'm skeptic about how much actual safety it will provide, especially considering the amount of work to mock each and every api response. Also not gonna be fun when a new version of Camunda rolls around. I think it can be used to do some basic testing, but I don't know about full test suite.
- We could add a set of integration tests, that actually hit the api. A simple docker container script can be added to spin up a bare bones Camunda instance with H2 database and have process definitions included in the test set. Some early hacking proved this to be a doable without to much hassle.
- Such integrations tests could be of use in providing usage examples, and CI's such as Appveyor support docker as well.

I would be happy to provide you with a PR showing how this could work.

@jlucansky Whatever your thoughts are, please let me know :)

**Comment by jlucansky** [comment]
* What I see in the documentation and real results from API calls, the DateTime is serialized as local time meaning there is no "Z" postfix to indicate UTC or "+00:xy" for timezone. So using DateTimeOffset is little pointless to me or maybe I miss something?

* Existing unit test project is quite useless right now, we can change test suite/framework without any problems. I agreee with integration tests it would be amazing to have CI with docker and real camunda container. I didn't known that is possible with Appveyor.

**Comment by flyingpie** [comment]
This has been fixed with release 2.4.3.
