### ISSUE TITLE
FetchAndLock ExternalTask with TenantId

### ISSUE THREAD

**Issue by pk-picturepark** [jlucansky/Camunda.Api.Client#27]
Hi

With the release of Camunda BPM 7.10.0 it is now possible to fetch and lock external tasks by process definition and tenant id (https://blog.camunda.com/post/2018/11/camunda-bpm-7100-released/).

Have you planned to enhance the Camunda.Api.Client library to support this feature anytime soon?

Thanks

**Comment by flyingpie** [comment]
@pk-picturepark You can find the PR for this here:
https://github.com/jlucansky/Camunda.Api.Client/pull/28

There's a prerelease package available from MyGet if you would like to try it out now.

@jlucansky Feel free to let me know if you have any comments about the PR.

**Comment by jlucansky** [comment]
All good as always :) Releasing nuget..
