### ISSUE TITLE
ErrorMessage and Variables support for ExternalTaskBpmnError

### ISSUE THREAD

**Issue by tscharli** [jlucansky/Camunda.Api.Client#29]
Hi @jlucansky 

Would it be possible to extend the method ExternalTaskResource.HandleBpmnError(ExternalTaskBpmnError externalTaskBpmnError) to support ErrorMessage and Variables as it was specified in v7.10 (https://docs.camunda.org/manual/7.10/reference/rest/external-task/post-bpmn-error/)?

Thanks in advance!

**Comment by jlucansky** [comment]
Should be covered: https://github.com/jlucansky/Camunda.Api.Client/commit/da1a836a0455b0baef625252200f07663d8930ee
