### ISSUE TITLE
DateTime Serialisation

### ISSUE THREAD

**Issue by darrenhull** [jlucansky/Camunda.Api.Client#30]
When using this library to get User Tasks that have been activated within the last minute I get the following error:

> Camunda.Api.Client: Can not construct instance of java.util.Date from String value '2019-02-05T09:48:46.1118058Z': not a valid representation (error: Failed to parse Date value '2019-02-05T09:48:46.1118058Z': Unparseable date: "2019-02-05T09:48:46.1118058Z")
 at [Source: org.camunda.bpm.engine.rest.filter.EmptyBodyFilter$1$1@70085f00; line: 1, column: 128] (through reference chain: org.camunda.bpm.engine.rest.dto.task.TaskQueryDto["createdAfter"]).

The code I am using is:

~~~~
            var camunda = CamundaClient.Create("http://localhost:8052/engine-rest");
            var humanTaskQuery = new TaskQuery() { Active = true };
            humanTaskQuery.CreatedAfter = DateTime.UtcNow.AddMinutes(-1);
            var userTasks = await camunda.UserTasks.Query(humanTaskQuery).List();

            foreach (var task in userTasks)
            {
                log.LogInformation($"Human Task {task.FormKey} Activated");
            }
~~~~

So this appears to be a simple datetime formatting issue, however this library does not provide a way to override the serializer settings.

I'm also wondering if i'm doing something wrong as most people should have run into this issue? Is this the best way to just get newly activated tasks?

**Comment by jlucansky** [comment]
It is related to this https://forum.camunda.org/t/engine-rest-date-format-bug/6105/7
I am working on solution.

**Comment by jlucansky** [comment]
Fixed https://github.com/jlucansky/Camunda.Api.Client/commit/d880df60677bde14a5503d0c0ad895b039abe03c

**Comment by darrenhull** [comment]
Thanks

**Comment by darrenhull** [comment]
This is still an issue the API returns a 400 error now.

**Comment by darrenhull** [comment]
I have a fix I will submit a PR.
