### ISSUE TITLE
Submit File when starting a new Process

### ISSUE THREAD

**Issue by nicentra** [jlucansky/Camunda.Api.Client#31]
Is there any support for submitting/uploading any kind of file when submitting the starting Form for a process, so far I am only able to submit it as bytestream but I don't how to submit as an actual file.

Sincerely,
Mike

**Comment by jlucansky** [comment]
Hi, you can use this snippet with latest version:
```cs
var form = new SubmitStartForm();
form.Variables.Add("file1", VariableValue.FromFile("C:\\excel1.xlsx", Iana.MediaTypes.Application.VndMsExcel));
await client.ProcessDefinitions["proc-name1"].SubmitForm(form);
```

**Comment by nicentra** [comment]
> Hi, you can use this snippet with latest version:
> 
> ```cs
> var form = new SubmitStartForm();
> form.Variables.Add("file1", VariableValue.FromFile("C:\\excel1.xlsx", Iana.MediaTypes.Application.VndMsExcel));
> await client.ProcessDefinitions["proc-name1"].SubmitForm(form);
> ```

Hey thanks for the reply, unfortunately, it doesn't seem to work as my file arrives with 0 bytes on the camunda application server. I am uploading/attaching a simple 6kb PDF file.

```cs
var form = new SubmitStartForm();
form.Variables.Add("test", VariableValue.FromObject(rInt));
var vv = VariableValue.FromFile(fiTemp.FullName, Iana.MediaTypes.Application.Pdf);
form.Variables.Add("invoiceDocument", vv);
var processInfo = await camunda.ProcessDefinitions.ByKey("dummy").SubmitForm(form);
```  

`fiTemp` is a fileinfo variable received by iterating over a directory
This my code

**Comment by jlucansky** [comment]
Content of files is not downloaded when querying with:
```cs
await camunda.ProcessInstances[processInfo.Id].Variables.GetAll();
```
You must explicitly download file with GetBinary method:
```cs
await camunda.ProcessInstances[processInfo.Id].Variables.GetBinary("invoiceDocument");
```

**Comment by nicentra** [comment]
I'm not trying to download a document/file. I'm trying to create a process and upload a file with it whenever a new document is deposited on the fileserver

**Comment by jlucansky** [comment]
I just tried with demo BPMN diagram shipped with Camunda default installation

```cs
var form = new SubmitStartForm();
form.Variables.Add("invoiceDocument", VariableValue.FromFile("C:\\doc1.pdf", Iana.MediaTypes.Application.Pdf));
form.Variables.Add("amount", VariableValue.FromObject(1.1));
form.Variables.Add("invoiceCategory", VariableValue.FromObject("Test"));
form.Variables.Add("invoiceClassification", VariableValue.FromObject("c1"));

var procInst = await client.ProcessDefinitions.ByKey("invoice").SubmitForm(form);
```

Then invoiceDocument can be downloaded successfully via Camunda Cockpit web UI so it's been properly uploaded.

**Comment by nicentra** [comment]
Hey quick update,

the methods work, I identified a potential bug which is messing with the file. In my dummy process I create a task which is immediately in the service task phase and gets pulled by a worker (LockAndFetch) and transitions to a User Task, during that transition the file gets lost and I don't why yet.

Thank you for clarifying and all the work you put into this!

Cheers

**Comment by nicentra** [comment]
Last update, 

I figured the issue out, it was on my side!

When completing a task after fetching it I used the following snippet

```cs
camunda.ExternalTasks[externalTask.Id].Complete(new CompleteExternalTask() {
        Variables = externalTask.Variables,
        WorkerId = externalTask.WorkerId
});
```
Apparently `Variables = externalTask.Variables` messed with the file that was being uploaded and I didn't realise it was unnecessary to do so! The issue can be closed, thank you so much for the help and work!
