### ISSUE TITLE
ExternalTaskResource.Complete with LocalVariables

### ISSUE THREAD

**Issue by hangy** [jlucansky/Camunda.Api.Client#33]
The [`CompleteExternalTask`](https://github.com/jlucansky/Camunda.Api.Client/blob/35f998bb1fdf5ba0326ad34bf85358e061fe5dba/Camunda.Api.Client/ExternalTask/CompleteExternalTask.cs) class does not support posting [`localVariables`](https://docs.camunda.org/manual/7.10/reference/rest/external-task/post-complete/#request-body) when completing an external task. This would be helpful to post variables that can be used in [execution listeners](https://forum.camunda.org/t/external-client-local-variables-scope/8793/3).

**Comment by hangy** [comment]
As a workaround, I've found out that the variable is available in the execution listener if it's set like this:
```
this.camunda.Executions[task.ExecutionId].LocalVariables.Set(
    "variableName",
    VariableValue.FromObject("variableValue"));
```

**Comment by jlucansky** [comment]
The CompleteExternalTask contains LocalVariables now.

**Comment by hangy** [comment]
Thank you! :+1:
