### ISSUE TITLE
How do you start a process?

### ISSUE THREAD

**Issue by davidpipes** [jlucansky/Camunda.Api.Client#36]
I am looking to use this and was wondering if someone could help me with starting a process with and without variables defined?

I managed to do some simpler requests and I am having trouble finding any documentation or test cases.

**Comment by davidpipes** [comment]
I think I might have answered my own question.

`
// Set Client.
            CamundaClient camunda = CamundaClient.Create("http://localhost:8081/engine-rest");

            // Get Process List.
            var processList = await camunda.ProcessDefinitions.Query().List();

            // Get Process by id.
            var process = await camunda.ProcessDefinitions["test-process:1:7671d32b-a282-11e9-94bc-9c305b1f6ba6"].Get();

            // Start a process with no variables.
            var testNoVars = await camunda.ProcessDefinitions["test-process:1:7671d32b-a282-11e9-94bc-9c305b1f6ba6"].StartProcessInstance(new StartProcessInstance());

            // Start a process with variables.
            StartProcessInstance i = new StartProcessInstance();
            i.SetVariable("Test1", "TEST");
            i.SetVariable("Test2", "TEST2");
            i.SetVariable("Test3", "TEST3");
            var testVars = await camunda.ProcessDefinitions["test-process:1:7671d32b-a282-11e9-94bc-9c305b1f6ba6"].StartProcessInstance(i);
`

Let me know if this isn't the best way to go about this.

**Comment by jlucansky** [comment]
Yes, you figured it out correctly :)
