### ISSUE TITLE
Wrong version in nuGet 2.4.2

### ISSUE THREAD

**Issue by adolja** [jlucansky/Camunda.Api.Client#37]
I still get Java date exceptions even after updating my nuGet to version 2.4.2 so I decided to decompile dll and saw that latest version of the code is not included in nuGet.

![image](https://user-images.githubusercontent.com/7592425/62046945-7d691800-b209-11e9-9600-0da366ad0058.png)

**Comment by jlucansky** [comment]
Please confirm with latest 2.4.3

**Comment by adolja** [comment]
I can confirm that version 2.4.3 fixes this issue
