### ISSUE TITLE
Make it possible to retrieve external task error Details

### ISSUE THREAD

**Issue by plukawski** [jlucansky/Camunda.Api.Client#40]
Good day,
Is there any way to obtain errorDetails for a failed external task? The ExternalTaskInfo class does not have errorDetails property and I do not see any action available for External Tasks service in this client library that can be able to obtain that information.
Using postman I have checked that I have to call the following endpoint to obtain the error details for failed external task which works fine:
`GET /external-task/{id}/errorDetails`. 
Here I find the other issue - according to the Camunda REST API Reference documentation there is no such endpoint available at all. Does that mean that retrieving errorDetails for a failed external task is not officially supported?

**Comment by jlucansky** [comment]
Resolved by adding ErrorDetails to ExternalTaskInfo https://github.com/jlucansky/Camunda.Api.Client/commit/6aafcd1fc3c1fdcd739a5df33791fb076e62d8f0
