### ISSUE TITLE
Business Key property missing from External Task

### ISSUE THREAD

**Issue by blong145** [jlucansky/Camunda.Api.Client#42]
Whenever you make a call using the fetch and lock method on External Tasks, the returned object doesn't have the businessKey property. Seems like the business key (businessKey) property is missing from the ExternalTaskInfo.cs file. Can this be added considering it's returned in the Camunda API as a property from the fetch call?

https://docs.camunda.org/manual/latest/reference/rest/external-task/fetch/

Is this intentionally left out?

A quick and dirty solution is to make another query to get the process instance (which does have the business key property), but it seems like adding the business key to the external task object would be a more correct solution.

**Comment by davidpipes** [comment]
I too am having this issue. Also in the get /externalTask it is missing there as well.

**Comment by jlucansky** [comment]
Merged PR https://github.com/jlucansky/Camunda.Api.Client/pull/47
