### ISSUE TITLE
Cannot test handling of ApiExceptions because there is no public constructor

### ISSUE THREAD

**Issue by gaensebluemchenritter** [jlucansky/Camunda.Api.Client#49]
As it states in the title - in our project we cannot unit test the handling of ApiException or derived Exceptions, because they don't expose any public constructor.

While we have been able to mitigate the absence of interface definitions for CamundaClient, *Service classes and *Resource classes so far (by defining wrapper interfaces and classes), we cannot do so with the exceptions. Since we want to handle ApiExceptions differently to other exceptions and we want to test this behavior, some way of creating an ApiException (and specific derived exceptions) would be more than handy.

**Comment by flyingpie** [comment]
@gaensebluemchenritter I just created a PR which opens up the exception constructors, and I have a preview package here:

https://www.myget.org/feed/flyingpie/package/nuget/Camunda.Api.Client

Could you let me know if this solves your problem?

**Comment by gaensebluemchenritter** [comment]
As I've already stated in the comments to the corresponding pull request: works like a charm for us!

**Comment by gaensebluemchenritter** [comment]
Ok, so now I have a new problem: when I force Camunda into returning a 404 (for example) I get an exception - but not a Camunda.Api.Client ApiException (RestException in that case, as the error message indicates), but a Refit.ApiException. I could not find any Refit.ApiException handling in the code (at least nothing that came in mind), and RestException is never used in any part of the code. Is this a known issue or (rather likely) am I missing something crucial?

**Comment by gaensebluemchenritter** [comment]
Ignore that, it was just me being stupid - using the ErrorMessageHandler instead of the HttpMessageHandler did the trick!

**Comment by jlucansky** [comment]
Merged
