### ISSUE TITLE
Migration Support

### ISSUE THREAD

**Issue by roofman2008** [jlucansky/Camunda.Api.Client#53]
Can you implement the migration integration with camunda engine.

**Comment by gaensebluemchenritter** [comment]
You could try this ad hoc version of mine:

https://github.com/gaensebluemchenritter/Camunda.Api.Client/tree/AddMissingServiceEndpoints

Please be aware that this version makes use of Refit 5.0.23, so if you are using Refit additionally to Camunda.Api.Client you could run into some version conflicts.

If you run into any problems, let me know.

**Comment by jlucansky** [comment]
Migrations and CaseInstances are in PR #56 merged from 
https://github.com/gaensebluemchenritter/Camunda.Api.Client/tree/AddMissingServiceEndpoints
