### ISSUE TITLE
Strong-named assembly

### ISSUE THREAD

**Issue by PMudra** [jlucansky/Camunda.Api.Client#54]
Firstly, thanks for publishing this library!

I am working in an environment where all assemblies are strong-named. That means that I could only use this library in my project when it is also strong-named.

Feature request: Please publish a strong-named version of the assembly.

Hints:
- https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named
- The Refit assemblies are strong-named since version 5.

**Comment by gaensebluemchenritter** [comment]
So basically this would also need Camunda.Api.Client to use Refit 5 ...

**Comment by PMudra** [comment]
Exactly and I guess that's what you did in #55

**Comment by jlucansky** [comment]
Resolved in version 2.5.1
