### ISSUE TITLE
Support for .NET Standard

### ISSUE THREAD

**Issue by jasonchester** [jlucansky/Camunda.Api.Client#6]
In order to leverage camunda from .NET core applications, release the API as a .NET standard library.

The latest version of Refit targets **netstandard1.4** so it should be straightforward for Camunda.Api.Client to target the same. https://github.com/paulcbetts/refit/blob/master/Refit/Refit.csproj#L5

**Comment by jasonchester** [comment]
@jlucansky any update on this? I may have a team that could help with this but would like to understand if you are still maintaining this project or not.

**Comment by jlucansky** [comment]
Yes, I am maintaining but currently I really don’t have much time to support .NET Standard so if you insist and have some resources it is great. I can give you colab access to the repository if you need.

**Comment by windischb** [comment]
#7

**Comment by jlucansky** [comment]
Thank you very much, I'll take a look

**Comment by neilst** [comment]
Hi 

Has there been any progress on this ?

**Comment by jlucansky** [comment]
I see there was just released refit 4.1 so finally I can merge

**Comment by neilst** [comment]
@jlucansky & @windischb - looks like there may be an additional issue with Refit.
Looking at https://github.com/jlucansky/refit/commit/4c273b923376164c23b5e7b32efd017cdf754e2f
Deployments will fail - missing HttpContent check and IEnumerable<HttpContent>
