### ISSUE TITLE
Use `ErrorMessageHandler` with a custom HttpClient

### ISSUE THREAD

**Issue by nicojs** [jlucansky/Camunda.Api.Client#8]
The constructor of `CamundaClient` allows for an `httpClient` parameter. We use this overload, because it gives us the ability to configure the client to use authentication.

Unfortunately this makes that we cannot use the default [`ErrorMessageHandler`](https://github.com/jlucansky/Camunda.Api.Client/blob/35f998bb1fdf5ba0326ad34bf85358e061fe5dba/Camunda.Api.Client/ErrorMessageHandler.cs) class, as it is internal.

Could this class be made `public`? So we can use it with a custom `HttpClient`?

**Comment by jlucansky** [comment]
Yes it can be public. https://github.com/jlucansky/Camunda.Api.Client/commit/cc33bd12a95eb4007b895940b25eaf6da2188355
