### ISSUE TITLE
UserTaskService missing end points

### ISSUE THREAD

**Issue by neilst** [jlucansky/Camunda.Api.Client#9]
Hi,

It appears that a revert to the UserTaskService was made  [here](https://github.com/jlucansky/Camunda.Api.Client/commit/bf24eddfc7d63b7bc7037cdce604df1f37c1fcdf). 
What was the reason for this as I would like to make use of Complete task etc.

**Comment by jlucansky** [comment]
User Task actions like Complete is already in https://github.com/jlucansky/Camunda.Api.Client/blob/master/Camunda.Api.Client/UserTask/TaskResource.cs#L66
